# Generated by Django 4.1 on 2022-10-05 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dosen',
        ),
        migrations.DeleteModel(
            name='Mahasiswa',
        ),
        migrations.DeleteModel(
            name='Tendik',
        ),
    ]
