# Generated by Django 4.1 on 2022-10-05 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_mahasiswa_tendik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=200)),
                ('Keterangan', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='dosen',
            name='Fakultas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='about.fakultas'),
        ),
    ]
